### ISSUE TITLE
Add command to add github package to zig.mod

### ISSUE THREAD

**Issue by xxami** [nektro/zigmod#17]
Small feature request, we currently write this in zig.mod
```
dev_dependencies:
  - src: git https://github.com/user/package
    name: packagename
    main: src/main.zig
```

For packages not on zpm and only on github, it would be convenient to include a shortcut to add this like some other languages do:

```sh
$ zigmod add --git user/package
```

This will make it easier for users to get up and running with everyones packages too.
