### ISSUE TITLE
Cannot import and use a dependency

### ISSUE THREAD

**Issue by ducdetronquito** [nektro/zigmod#44]
Hi @nektro ,

I think I encountered a bug or it can be just be me misusing zigmod !

**Steps to reproduce**:
I created a small library [zigmod_dep](https://github.com/ducdetronquito/zigmod_dep) that provide an `add` function.
(To create the library, I juste used `zig init-lib` and `zigmod init`)

I created an other library [zigmod_base](https://github.com/ducdetronquito/zigmod_base) that uses `zigmod_dep.add`.
(To create the library, I juste used `zig init-lib` and `zigmod init`)

When running the tests of `zigmod_base`, it does not find the `zigmod_dep` package and crashes with the following error:

```
λ zig build test
.\src\main.zig:3:20: error: unable to find 'zigmod_dep'
const zigmod_dep = @import("zigmod_dep");
                   ^
.\src\main.zig:6:12: note: referenced here
    return zigmod_dep.add(a, a);
           ^
The following command exited with error code 1:
C:\Program Files (x86)\Zig\0.9.0\zig.exe test C:\Users\DEV\Documents\Code\tests\zigmod_base\src\main.zig --cache-dir C:\Users\DEV\Documents\Code\tests\zigmod_base\zig-cache --global-cache-dir C:\Users\DEV\AppData\Local\zig --name test --pkg-begin zigmod_base C:\Users\DEV\Documents\Code\tests\zigmod_base\src\main.zig --pkg-begin zigmod_dep C:\Users\DEV\Documents\Code\tests\zigmod_base\.zigmod\deps\git\github.com\ducdetronquito\zigmod_dep\src\main.zig --pkg-end --pkg-end

error: the following build command failed with exit code 1:
C:\Users\DEV\Documents\Code\tests\zigmod_base\zig-cache\o\8f0600972eaf8c537216c8b7e5934962\build.exe C:\Program Files (x86)\Zig\0.9.0\zig.exe C:\Users\DEV\Documents\Code\tests\zigmod_base C:\Users\DEV\Documents\Code\tests\zigmod_base\zig-cache C:\Users\DEV\AppData\Local\zig test
```

To fix the error, and be able to compile I just patched `deps.zig` in `zigmod_base` as such:

```zig

// Before
pub const packages = &[_]Package{
    package_data._muh5sqkmx04g,
};

// After
pub const packages = &[_]Package{
    package_data._muh5sqkmx04g,
    package_data._cyghmh8qzz6y,
};
```

I hope I have clear enough to help you reproduce it :)

**Comment by xyaman** [comment]
I have the same error and patching `deps.zig` following @ducdetronquito step fixed it.

**Comment by nektro** [comment]
in `zigmod_base`, [this line](https://github.com/ducdetronquito/zigmod_base/blob/master/build.zig#L8) and [this line](https://github.com/ducdetronquito/zigmod_base/blob/master/zig.mod#L3) should not point to the same file. the latter is for the use case of making a "library" in the sense a package that others may depend on. thus you may depend on the internal package yourself by doing `@import("zigmod_base")`.

for your use case however it appears, given the edit you made, that what you want is for (this line)[https://github.com/ducdetronquito/zigmod_base/blob/master/zig.mod#L3] to be removed and (this line)[https://github.com/ducdetronquito/zigmod_base/blob/master/zig.mod#L6] be changed to say `root_dependencies:`. after those changes rerunning `zigmod fetch` should give you the `deps.zig` you desire.

**Comment by ducdetronquito** [comment]
Hi @nektro !

I don't understand you first paragraph, because in this case both `zigmod_base` and `zigmod_dep` are libraries.

I will try to describe my actual situation and not an example, maybe it will be more clear !

- [http](https://github.com/ducdetronquito/http) is a library with no dependencies.
- [h11](https://github.com/ducdetronquito/h11) is a library that depends on [http](https://github.com/ducdetronquito/http)
- [requestz](https://github.com/ducdetronquito/requestz) is a library that depends on [h11](https://github.com/ducdetronquito/h11), [http](https://github.com/ducdetronquito/http), [zig-network](https://github.com/MasterQ32/zig-network) and [iguanaTLS](https://github.com/nektro/iguanaTLS).

I edited the zig.mod files of each libraries following your advice of the second paragraph.
(I read the doc but I still don't understand the difference between a dependency and a root_dependency :/)
As a result, I can run tests (`zig build test`) for `h11` but I can't for `requestz` because the compiler does find the `h11` package.

Here is the zig.mod files of each libraries:
```yml
# http zig.mod
id: a2vh8na282lel0as4l57ibmjje9oqt2o2fajm5hofpsbqoa8
name: http
main: src/main.zig
license: 0BSD
description: HTTP core types for Zig 🦴
dependencies:
```

```yml
# h11 zig.mod
id: 7noqknvqkyyup91axamyzfiet5r41k9apsb9wzbn9ay3l2jc
name: h11
license: 0BSD
description: I/O agnostic HTTP/1.1 implementation for Zig 🦎
root_dependencies:
  - src: git https://github.com/ducdetronquito/http branch-release/0.2.0
```

```yml
# requestz zig.mod
id: 86gq5kz04nyy4e7eq2njytvqivd2unre6i965ol3p5gz7cw3
name: requestz
license: 0BSD
description: HTTP client for Zig 🦎
root_dependencies:
   - src: git https://github.com/nektro/iguanaTLS commit-d49c382
   - src: git https://github.com/MasterQ32/zig-network commit-b9c5282
   - src: git https://github.com/ducdetronquito/http branch-release/0.2.0
   - src: git https://github.com/ducdetronquito/h11 branch-release/0.2.0
```

What am I missing ^^ ?

Thanks in advance, and have a nice day !

**Comment by ducdetronquito** [comment]
After toying a bit, here are the zig.mod files that each library importable from another library along with its dependencies, and being able to run tests on each library.

```yaml
# http zig.mod
id: a2vh8na282lel0as4l57ibmjje9oqt2o2fajm5hofpsbqoa8
name: http
main: src/main.zig
license: 0BSD
description: HTTP core types for Zig 🦴
dependencies:
```

```yaml
# h11 zig.mod
id: 7noqknvqkyyup91axamyzfiet5r41k9apsb9wzbn9ay3l2jc
name: h11
license: 0BSD
description: I/O agnostic HTTP/1.1 implementation for Zig 🦎
root_dependencies:
  - src: git https://github.com/ducdetronquito/http branch-release/0.2.0
dependencies:
  - src: git https://github.com/ducdetronquito/http branch-release/0.2.0
 ```

```yaml
# requestz zig.mod
id: 86gq5kz04nyy4e7eq2njytvqivd2unre6i965ol3p5gz7cw3
name: requestz
license: 0BSD
description: HTTP client for Zig 🦎
root_dependencies:
   - src: git https://github.com/nektro/iguanaTLS commit-d49c382
   - src: git https://github.com/MasterQ32/zig-network commit-b9c5282
   - src: git https://github.com/ducdetronquito/http branch-release/0.2.0
   - src: git https://github.com/ducdetronquito/h11 branch-release/0.2.0
dependencies:
   - src: git https://github.com/nektro/iguanaTLS commit-d49c382
   - src: git https://github.com/MasterQ32/zig-network commit-b9c5282
   - src: git https://github.com/ducdetronquito/http branch-release/0.2.0
   - src: git https://github.com/ducdetronquito/h11 branch-release/0.2.0
```

Could you explain me why I must define both `dependencies` and `root_dependencies` ?
