### ISSUE TITLE
How to include a dependency that has a non-trivial build script

### ISSUE THREAD

**Issue by sigod** [nektro/zigmod#65]
Is it possible to add a library like [mach-glfw](https://github.com/hexops/mach-glfw) as a dependency?

Trying to add it like this:
```yml
root_dependencies:
  - src: git https://github.com/hexops/mach-glfw
    name: glfw
    main: src/main.zig
```

But getting these errors when attempting to compile:
```
$ zig build run
.\.zigmod\deps\git\github.com\hexops\mach-glfw\src\c.zig:18:15: error: C import failed
pub const c = @cImport({
              ^
.\.zigmod\deps\git\github.com\hexops\mach-glfw\src\c.zig:18:15: note: libc headers not available; compilation does not link against libc
pub const c = @cImport({
              ^
.\zig-cache\o\ec535826bac66f941930c9f5a2066914\cimport.h:2:10: note: 'GLFW/glfw3.h' file not found
#include <GLFW/glfw3.h>
         ^
```

Normally adding mach-glfw works like this:
```zig
// build.zig
const glfw = @import("libs/mach-glfw/build.zig");

// in fn build
exe.addPackagePath("glfw", "libs/mach-glfw/src/main.zig");
glfw.link(b, exe, .{});
```

**Comment by nektro** [comment]
maybe, zigmod does support adding c code, headers, and system libraries but those need to be defined in the `zigmod.yml` as well. or you define it as a `build_dependencies:` and then call the `.link` function

**Comment by sigod** [comment]
Oh, wow. It actually seems to work. Here's how I've done it:

In `zigmod.yml`:
```yml
root_dependencies:
  - src: git https://github.com/hexops/mach-glfw
    name: glfw
    main: src/main.zig
build_dependencies:
  - src: git https://github.com/hexops/mach-glfw
    name: glfw
    main: build.zig
```

In `build.zig`:
```zig
deps.imports.glfw.link(b, exe, .{});
```
