### ISSUE TITLE
`fetch` error: Can't import dependency

### ISSUE THREAD

**Issue by kassane** [nektro/zigmod#69]
My zigmod config:
```yaml
id: ahbjts2s3ajxyauijurs30fbtuq3zz5hemmhkp7newic332p
name: libzignes
main: src/main.zig
license: Apache-2.0
description: Zig Library for SNES development
dependencies:
  - src: git https://github.com/MasterQ32/SDL.zig
```
*Output:*

```bash
$> zigmod fetch
no zig.mod or zigmod.yml found and no override props defined. unable to use add this dependency!
```
---
Zigmod version: r78 (release build)
