### ISSUE TITLE
zigmod fetch panics on malformed zigmod.yml

### ISSUE THREAD

**Issue by not-rusty** [nektro/zigmod#76]
Or something like that.

Example configuration:
```yml
id: owwzd4yoivw3ux36rm4gz9t3byhbbtdlf9dxal6wm0vodan3
name: web-server
license: MIT
description: testing things
root_dependencies:
  - git https://github.com/Snektron/vulkan-zig <-- Missing src:
```

This fails with:

![image](https://user-images.githubusercontent.com/16207732/185084439-4054488b-178b-4ad5-9785-3457561cad49.png)

Adding the missing src: property fixes it.
