### ISSUE TITLE
`generate` subcommand only accounts for author's OS with `only_os`

### ISSUE THREAD

**Issue by TUSF** [nektro/zigmod#88]
In my zigmod.yml, I have:

```yaml
dependencies:
  - {
    src: git https://github.com/marlersoft/zigwin32,
    only_os: windows
  }
  - {
    src: system_lib dwrite,
    only_os: windows
  }
```

This works well enough when using the `fetch` subcommand, but if I use the `generate` subcommand, the generated `deps.zig` file will assume whoever is building the package is on the same OS as whoever ran `zigmod generate`.

This makes `generate` no different from `fetch` for libraries depending on OS-specific libraries & APIs.
